version: "3.9"

networks:
  my_network:
    # driver: bridge

services:

  web-core:
    container_name: nginx-web-test
    restart: unless-stopped
    image: nginx:stable-alpine
    volumes:
      - ./static-html:/usr/share/nginx/html
    ports:
      - 80:80
    networks:
      - my_network
